from enum import Enum


class ModelType(Enum):
    SSVAE = "SSVAE"
    DEEP_DETERMINISTIC_UNCERTAINTY = "DEEP_DETERMINISTIC_UNCERTAINTY"
    FEED_FORWARD_NN = "FEED_FORWARD_NN"
    MC_DROPOUT = "MC_DROPOUT"
    ENSEMBLES = "ENSEMBLES"
    VADAM = "VADAM"
